# Generated by Django 3.2.5 on 2021-07-25 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='product name')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('have_tax', models.BooleanField(default=False)),
                ('pdf_catalog', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='pdf catalog')),
                ('image_catalog', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image catalog')),
                ('technical_desc', models.TextField(verbose_name='technical description')),
                ('usable_for_organizations_product', models.ManyToManyField(to='organization.OrganizationsProduct', verbose_name='usable for organizations product')),
            ],
        ),
    ]
