# Generated by Django 3.2.5 on 2021-08-02 06:52

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_alter_organization_organization_name'),
        ('company', '0002_alter_companyproduct_pdf_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization', verbose_name='organization')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='qty')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('discount', models.FloatField(default=0, verbose_name='discount in percent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.companyproduct', verbose_name='product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellProcess.quote', verbose_name='quote')),
            ],
        ),
    ]
