# Generated by Django 3.2.5 on 2021-08-03 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellProcess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='expert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='expert'),
            preserve_default=False,
        ),
    ]
