# Generated by Django 3.2.5 on 2021-08-09 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellProcess', '0003_remove_quoteitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Follow Up Description')),
                ('created_on', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='expert')),
            ],
        ),
    ]
