# Generated by Django 3.2.5 on 2021-08-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellProcess', '0007_alter_followup_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='price'),
        ),
    ]
