# Generated by Django 3.2.5 on 2021-07-25 06:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product name')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20, verbose_name='Province')),
                ('organization_name', models.CharField(max_length=50, verbose_name='Organization name')),
                ('telephone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='This Landline number is Invalid.', regex='^0[0-9]{2,}[0-9]{7,}$')], verbose_name='Organization telephone')),
                ('workers_qty', models.PositiveIntegerField(default=1, verbose_name='Workers Quantity')),
                ('representative_full_name', models.CharField(max_length=80, verbose_name='Representative fullname')),
                ('representative_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='This Phone number is Invalid.', regex='09(1[0-9]|3[1-9]|2[1-9])-?[0-9]{3}-?[0-9]{4}')], verbose_name='Representative phone number')),
                ('representative_email', models.EmailField(max_length=254, verbose_name='Representative email')),
                ('created_on', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Expert')),
                ('manufactured_product', models.ManyToManyField(to='organization.OrganizationsProduct', verbose_name='Manufactured product')),
            ],
        ),
    ]
