# Generated by Django 3.2.5 on 2021-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Organization name'),
        ),
    ]
